networks:
  application:
    driver: bridge


################################
#       Backend Todo-list      #
################################
services:
  backend:
    restart: always
    ports:
      - 8080:8080
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - application