networks:
  application:
    driver: bridge

volumes:
  mongodb_data:


services:

  ################################
  #           Database           #
  ################################
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongolone
      MONGO_INITDB_ROOT_PASSWORD: mongolonepw
    networks:
      - application
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3


  ################################
  #       Backend Todo-list      #
  ################################
  backend:
    restart: always
    ports:
      - 8080:8080
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    volumes:
      - ./backend:/app
    networks:
      - application
    depends_on:
      mongodb:
        condition: service_healthy

  ################################
  #       Frontend Todo-list      #
  ################################
  frontend:
    ports:
      - 3000:3000
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - application
    depends_on:
      mongodb:
        condition: service_healthy